// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.21.9
// source: world.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 数据帧类型美剧
type ActionType int32

const (
	ActionType_SPWAN          ActionType = 0
	ActionType__MOVE          ActionType = 1
	ActionType_Destroy        ActionType = 2
	ActionType_Hide           ActionType = 3
	ActionType_PLAY_ANIMATION ActionType = 4
	ActionType_STOP_ANIMATION ActionType = 5
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "SPWAN",
		1: "_MOVE",
		2: "Destroy",
		3: "Hide",
		4: "PLAY_ANIMATION",
		5: "STOP_ANIMATION",
	}
	ActionType_value = map[string]int32{
		"SPWAN":          0,
		"_MOVE":          1,
		"Destroy":        2,
		"Hide":           3,
		"PLAY_ANIMATION": 4,
		"STOP_ANIMATION": 5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_world_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_world_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

type SimulateRPCMethod int32

const (
	SimulateRPCMethod_MOVE SimulateRPCMethod = 0
)

// Enum value maps for SimulateRPCMethod.
var (
	SimulateRPCMethod_name = map[int32]string{
		0: "MOVE",
	}
	SimulateRPCMethod_value = map[string]int32{
		"MOVE": 0,
	}
)

func (x SimulateRPCMethod) Enum() *SimulateRPCMethod {
	p := new(SimulateRPCMethod)
	*p = x
	return p
}

func (x SimulateRPCMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulateRPCMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_world_proto_enumTypes[1].Descriptor()
}

func (SimulateRPCMethod) Type() protoreflect.EnumType {
	return &file_world_proto_enumTypes[1]
}

func (x SimulateRPCMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulateRPCMethod.Descriptor instead.
func (SimulateRPCMethod) EnumDescriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

type SimulateRPCTicketCode int32

const (
	SimulateRPCTicketCode_OK     SimulateRPCTicketCode = 0
	SimulateRPCTicketCode_FAILED SimulateRPCTicketCode = 1
)

// Enum value maps for SimulateRPCTicketCode.
var (
	SimulateRPCTicketCode_name = map[int32]string{
		0: "OK",
		1: "FAILED",
	}
	SimulateRPCTicketCode_value = map[string]int32{
		"OK":     0,
		"FAILED": 1,
	}
)

func (x SimulateRPCTicketCode) Enum() *SimulateRPCTicketCode {
	p := new(SimulateRPCTicketCode)
	*p = x
	return p
}

func (x SimulateRPCTicketCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SimulateRPCTicketCode) Descriptor() protoreflect.EnumDescriptor {
	return file_world_proto_enumTypes[2].Descriptor()
}

func (SimulateRPCTicketCode) Type() protoreflect.EnumType {
	return &file_world_proto_enumTypes[2]
}

func (x SimulateRPCTicketCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SimulateRPCTicketCode.Descriptor instead.
func (SimulateRPCTicketCode) EnumDescriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2}
}

type Vector3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float64 `protobuf:"fixed64,1,opt,name=x,proto3,oneof" json:"x,omitempty"`
	Y *float64 `protobuf:"fixed64,2,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Z *float64 `protobuf:"fixed64,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
}

func (x *Vector3) Reset() {
	*x = Vector3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Vector3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector3) ProtoMessage() {}

func (x *Vector3) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector3.ProtoReflect.Descriptor instead.
func (*Vector3) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{0}
}

func (x *Vector3) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Vector3) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Vector3) GetZ() float64 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

type Quaternion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X *float64 `protobuf:"fixed64,1,opt,name=x,proto3,oneof" json:"x,omitempty"`
	Y *float64 `protobuf:"fixed64,2,opt,name=y,proto3,oneof" json:"y,omitempty"`
	Z *float64 `protobuf:"fixed64,3,opt,name=z,proto3,oneof" json:"z,omitempty"`
	W *float64 `protobuf:"fixed64,4,opt,name=w,proto3,oneof" json:"w,omitempty"`
}

func (x *Quaternion) Reset() {
	*x = Quaternion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quaternion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quaternion) ProtoMessage() {}

func (x *Quaternion) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quaternion.ProtoReflect.Descriptor instead.
func (*Quaternion) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{1}
}

func (x *Quaternion) GetX() float64 {
	if x != nil && x.X != nil {
		return *x.X
	}
	return 0
}

func (x *Quaternion) GetY() float64 {
	if x != nil && x.Y != nil {
		return *x.Y
	}
	return 0
}

func (x *Quaternion) GetZ() float64 {
	if x != nil && x.Z != nil {
		return *x.Z
	}
	return 0
}

func (x *Quaternion) GetW() float64 {
	if x != nil && x.W != nil {
		return *x.W
	}
	return 0
}

type PlayerJoin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 玩家UUID
}

func (x *PlayerJoin) Reset() {
	*x = PlayerJoin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoin) ProtoMessage() {}

func (x *PlayerJoin) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoin.ProtoReflect.Descriptor instead.
func (*PlayerJoin) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerJoin) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type PlayerQuit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 玩家UUID
}

func (x *PlayerQuit) Reset() {
	*x = PlayerQuit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerQuit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQuit) ProtoMessage() {}

func (x *PlayerQuit) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQuit.ProtoReflect.Descriptor instead.
func (*PlayerQuit) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerQuit) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type SpwanObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     *string     `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`         // 对象ID
	Position *Vector3    `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"` // 对象位置
	Rotation *Quaternion `protobuf:"bytes,3,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"` // 对象旋转
	Scale    *Vector3    `protobuf:"bytes,4,opt,name=scale,proto3,oneof" json:"scale,omitempty"`       // 对象比例
}

func (x *SpwanObject) Reset() {
	*x = SpwanObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpwanObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpwanObject) ProtoMessage() {}

func (x *SpwanObject) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpwanObject.ProtoReflect.Descriptor instead.
func (*SpwanObject) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{4}
}

func (x *SpwanObject) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *SpwanObject) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *SpwanObject) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *SpwanObject) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

type MoveObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     *string     `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	Position *Vector3    `protobuf:"bytes,2,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Rotation *Quaternion `protobuf:"bytes,3,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	Scale    *Vector3    `protobuf:"bytes,4,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
}

func (x *MoveObject) Reset() {
	*x = MoveObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveObject) ProtoMessage() {}

func (x *MoveObject) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveObject.ProtoReflect.Descriptor instead.
func (*MoveObject) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{5}
}

func (x *MoveObject) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *MoveObject) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *MoveObject) GetRotation() *Quaternion {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *MoveObject) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

type DestroyObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid *string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
}

func (x *DestroyObject) Reset() {
	*x = DestroyObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DestroyObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyObject) ProtoMessage() {}

func (x *DestroyObject) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyObject.ProtoReflect.Descriptor instead.
func (*DestroyObject) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{6}
}

func (x *DestroyObject) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type HideObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid *string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
}

func (x *HideObject) Reset() {
	*x = HideObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HideObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HideObject) ProtoMessage() {}

func (x *HideObject) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HideObject.ProtoReflect.Descriptor instead.
func (*HideObject) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{7}
}

func (x *HideObject) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type PlayAnimation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          *string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	AnimationUuid *string `protobuf:"bytes,2,opt,name=animation_uuid,json=animationUuid,proto3,oneof" json:"animation_uuid,omitempty"`
}

func (x *PlayAnimation) Reset() {
	*x = PlayAnimation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayAnimation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayAnimation) ProtoMessage() {}

func (x *PlayAnimation) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayAnimation.ProtoReflect.Descriptor instead.
func (*PlayAnimation) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{8}
}

func (x *PlayAnimation) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *PlayAnimation) GetAnimationUuid() string {
	if x != nil && x.AnimationUuid != nil {
		return *x.AnimationUuid
	}
	return ""
}

type StopAnimation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid          *string `protobuf:"bytes,1,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	AnimationUuid *string `protobuf:"bytes,2,opt,name=animation_uuid,json=animationUuid,proto3,oneof" json:"animation_uuid,omitempty"`
}

func (x *StopAnimation) Reset() {
	*x = StopAnimation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAnimation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAnimation) ProtoMessage() {}

func (x *StopAnimation) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAnimation.ProtoReflect.Descriptor instead.
func (*StopAnimation) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{9}
}

func (x *StopAnimation) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *StopAnimation) GetAnimationUuid() string {
	if x != nil && x.AnimationUuid != nil {
		return *x.AnimationUuid
	}
	return ""
}

// 同步数据帧请求
type SyncAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string     `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                                    // 同步请求的UUID
	Type      ActionType `protobuf:"varint,2,opt,name=type,proto3,enum=cluster_proto.ActionType" json:"type,omitempty"`     // 同步请求的类型
	CreatedAt *float64   `protobuf:"fixed64,3,opt,name=created_at,json=createdAt,proto3,oneof" json:"created_at,omitempty"` // 同步请求创建的时间，单位毫秒
	CreatorId *string    `protobuf:"bytes,4,opt,name=creator_id,json=creatorId,proto3,oneof" json:"creator_id,omitempty"`   // 同步请求创建者的ID
	// Types that are assignable to Payload:
	//	*SyncAction_Spwan
	//	*SyncAction_Move
	//	*SyncAction_Destory
	//	*SyncAction_Hide
	//	*SyncAction_PlayAnim
	//	*SyncAction_StopAnim
	Payload isSyncAction_Payload `protobuf_oneof:"payload"`
}

func (x *SyncAction) Reset() {
	*x = SyncAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAction) ProtoMessage() {}

func (x *SyncAction) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAction.ProtoReflect.Descriptor instead.
func (*SyncAction) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{10}
}

func (x *SyncAction) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *SyncAction) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_SPWAN
}

func (x *SyncAction) GetCreatedAt() float64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *SyncAction) GetCreatorId() string {
	if x != nil && x.CreatorId != nil {
		return *x.CreatorId
	}
	return ""
}

func (m *SyncAction) GetPayload() isSyncAction_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *SyncAction) GetSpwan() *SpwanObject {
	if x, ok := x.GetPayload().(*SyncAction_Spwan); ok {
		return x.Spwan
	}
	return nil
}

func (x *SyncAction) GetMove() *MoveObject {
	if x, ok := x.GetPayload().(*SyncAction_Move); ok {
		return x.Move
	}
	return nil
}

func (x *SyncAction) GetDestory() *DestroyObject {
	if x, ok := x.GetPayload().(*SyncAction_Destory); ok {
		return x.Destory
	}
	return nil
}

func (x *SyncAction) GetHide() *HideObject {
	if x, ok := x.GetPayload().(*SyncAction_Hide); ok {
		return x.Hide
	}
	return nil
}

func (x *SyncAction) GetPlayAnim() *PlayAnimation {
	if x, ok := x.GetPayload().(*SyncAction_PlayAnim); ok {
		return x.PlayAnim
	}
	return nil
}

func (x *SyncAction) GetStopAnim() *StopAnimation {
	if x, ok := x.GetPayload().(*SyncAction_StopAnim); ok {
		return x.StopAnim
	}
	return nil
}

type isSyncAction_Payload interface {
	isSyncAction_Payload()
}

type SyncAction_Spwan struct {
	Spwan *SpwanObject `protobuf:"bytes,5,opt,name=spwan,proto3,oneof"`
}

type SyncAction_Move struct {
	Move *MoveObject `protobuf:"bytes,6,opt,name=move,proto3,oneof"`
}

type SyncAction_Destory struct {
	Destory *DestroyObject `protobuf:"bytes,7,opt,name=destory,proto3,oneof"`
}

type SyncAction_Hide struct {
	Hide *HideObject `protobuf:"bytes,8,opt,name=hide,proto3,oneof"`
}

type SyncAction_PlayAnim struct {
	PlayAnim *PlayAnimation `protobuf:"bytes,9,opt,name=play_anim,json=playAnim,proto3,oneof"`
}

type SyncAction_StopAnim struct {
	StopAnim *StopAnimation `protobuf:"bytes,10,opt,name=stop_anim,json=stopAnim,proto3,oneof"`
}

func (*SyncAction_Spwan) isSyncAction_Payload() {}

func (*SyncAction_Move) isSyncAction_Payload() {}

func (*SyncAction_Destory) isSyncAction_Payload() {}

func (*SyncAction_Hide) isSyncAction_Payload() {}

func (*SyncAction_PlayAnim) isSyncAction_Payload() {}

func (*SyncAction_StopAnim) isSyncAction_Payload() {}

// 数据帧同步反馈
type ActionCommitted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommittedAt    *float64 `protobuf:"fixed64,1,opt,name=committed_at,json=committedAt,proto3,oneof" json:"committed_at,omitempty"`          // 状态已同步的时间，单位毫秒
	SyncActionUuid *string  `protobuf:"bytes,2,opt,name=sync_action_uuid,json=syncActionUuid,proto3,oneof" json:"sync_action_uuid,omitempty"` // 同步请求的UUID
	CreatorId      *string  `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3,oneof" json:"creator_id,omitempty"`                  // 被同步者的ID
}

func (x *ActionCommitted) Reset() {
	*x = ActionCommitted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionCommitted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionCommitted) ProtoMessage() {}

func (x *ActionCommitted) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionCommitted.ProtoReflect.Descriptor instead.
func (*ActionCommitted) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{11}
}

func (x *ActionCommitted) GetCommittedAt() float64 {
	if x != nil && x.CommittedAt != nil {
		return *x.CommittedAt
	}
	return 0
}

func (x *ActionCommitted) GetSyncActionUuid() string {
	if x != nil && x.SyncActionUuid != nil {
		return *x.SyncActionUuid
	}
	return ""
}

func (x *ActionCommitted) GetCreatorId() string {
	if x != nil && x.CreatorId != nil {
		return *x.CreatorId
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RawMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *RawMessage) Reset() {
	*x = RawMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessage) ProtoMessage() {}

func (x *RawMessage) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessage.ProtoReflect.Descriptor instead.
func (*RawMessage) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{13}
}

func (x *RawMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FrameTick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tick   uint64          `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Mts    float64         `protobuf:"fixed64,2,opt,name=mts,proto3" json:"mts,omitempty"`
	Status []*EntityStatus `protobuf:"bytes,3,rep,name=status,proto3" json:"status,omitempty"`
}

func (x *FrameTick) Reset() {
	*x = FrameTick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrameTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameTick) ProtoMessage() {}

func (x *FrameTick) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameTick.ProtoReflect.Descriptor instead.
func (*FrameTick) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{14}
}

func (x *FrameTick) GetTick() uint64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *FrameTick) GetMts() float64 {
	if x != nil {
		return x.Mts
	}
	return 0
}

func (x *FrameTick) GetStatus() []*EntityStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type EntityStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tick      *uint64  `protobuf:"varint,2,opt,name=tick,proto3,oneof" json:"tick,omitempty"`
	ClientMts *float64 `protobuf:"fixed64,3,opt,name=client_mts,json=clientMts,proto3,oneof" json:"client_mts,omitempty"`
	Position  *Vector3 `protobuf:"bytes,4,opt,name=position,proto3,oneof" json:"position,omitempty"`
	Rotation  *Vector3 `protobuf:"bytes,5,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	Scale     *Vector3 `protobuf:"bytes,6,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
}

func (x *EntityStatus) Reset() {
	*x = EntityStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStatus) ProtoMessage() {}

func (x *EntityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStatus.ProtoReflect.Descriptor instead.
func (*EntityStatus) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{15}
}

func (x *EntityStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityStatus) GetTick() uint64 {
	if x != nil && x.Tick != nil {
		return *x.Tick
	}
	return 0
}

func (x *EntityStatus) GetClientMts() float64 {
	if x != nil && x.ClientMts != nil {
		return *x.ClientMts
	}
	return 0
}

func (x *EntityStatus) GetPosition() *Vector3 {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EntityStatus) GetRotation() *Vector3 {
	if x != nil {
		return x.Rotation
	}
	return nil
}

func (x *EntityStatus) GetScale() *Vector3 {
	if x != nil {
		return x.Scale
	}
	return nil
}

// State(n) + Input(n) = State(n+1)
type MoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Delta      *EntityStatus `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	Prediction *EntityStatus `protobuf:"bytes,3,opt,name=prediction,proto3,oneof" json:"prediction,omitempty"`
	ClientMts  float64       `protobuf:"fixed64,4,opt,name=client_mts,json=clientMts,proto3" json:"client_mts,omitempty"`
	ClientTick uint64        `protobuf:"varint,5,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
}

func (x *MoveRequest) Reset() {
	*x = MoveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRequest) ProtoMessage() {}

func (x *MoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRequest.ProtoReflect.Descriptor instead.
func (*MoveRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{16}
}

func (x *MoveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MoveRequest) GetDelta() *EntityStatus {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *MoveRequest) GetPrediction() *EntityStatus {
	if x != nil {
		return x.Prediction
	}
	return nil
}

func (x *MoveRequest) GetClientMts() float64 {
	if x != nil {
		return x.ClientMts
	}
	return 0
}

func (x *MoveRequest) GetClientTick() uint64 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

type MoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result     *EntityStatus `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	ClientMts  float64       `protobuf:"fixed64,2,opt,name=client_mts,json=clientMts,proto3" json:"client_mts,omitempty"`
	ClientTick uint64        `protobuf:"varint,3,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	Id         string        `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MoveResponse) Reset() {
	*x = MoveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResponse) ProtoMessage() {}

func (x *MoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResponse.ProtoReflect.Descriptor instead.
func (*MoveResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{17}
}

func (x *MoveResponse) GetResult() *EntityStatus {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *MoveResponse) GetClientMts() float64 {
	if x != nil {
		return x.ClientMts
	}
	return 0
}

func (x *MoveResponse) GetClientTick() uint64 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *MoveResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RawMessageGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawData [][]byte `protobuf:"bytes,1,rep,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
}

func (x *RawMessageGroup) Reset() {
	*x = RawMessageGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RawMessageGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMessageGroup) ProtoMessage() {}

func (x *RawMessageGroup) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMessageGroup.ProtoReflect.Descriptor instead.
func (*RawMessageGroup) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{18}
}

func (x *RawMessageGroup) GetRawData() [][]byte {
	if x != nil {
		return x.RawData
	}
	return nil
}

type SimulateRPCRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method     string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	ClientTick uint64   `protobuf:"varint,2,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	ClientMts  float64  `protobuf:"fixed64,3,opt,name=client_mts,json=clientMts,proto3" json:"client_mts,omitempty"`
	RawArgs    [][]byte `protobuf:"bytes,4,rep,name=raw_args,json=rawArgs,proto3" json:"raw_args,omitempty"`
}

func (x *SimulateRPCRequest) Reset() {
	*x = SimulateRPCRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateRPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRPCRequest) ProtoMessage() {}

func (x *SimulateRPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRPCRequest.ProtoReflect.Descriptor instead.
func (*SimulateRPCRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{19}
}

func (x *SimulateRPCRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *SimulateRPCRequest) GetClientTick() uint64 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *SimulateRPCRequest) GetClientMts() float64 {
	if x != nil {
		return x.ClientMts
	}
	return 0
}

func (x *SimulateRPCRequest) GetRawArgs() [][]byte {
	if x != nil {
		return x.RawArgs
	}
	return nil
}

type SimulateRPCTicket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code      uint32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	RequestId *string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3,oneof" json:"request_id,omitempty"`
}

func (x *SimulateRPCTicket) Reset() {
	*x = SimulateRPCTicket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateRPCTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRPCTicket) ProtoMessage() {}

func (x *SimulateRPCTicket) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRPCTicket.ProtoReflect.Descriptor instead.
func (*SimulateRPCTicket) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{20}
}

func (x *SimulateRPCTicket) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SimulateRPCTicket) GetRequestId() string {
	if x != nil && x.RequestId != nil {
		return *x.RequestId
	}
	return ""
}

type SimulateRPCResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId  string  `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Code       uint32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	ClientTick uint64  `protobuf:"varint,3,opt,name=client_tick,json=clientTick,proto3" json:"client_tick,omitempty"`
	ClientMts  float64 `protobuf:"fixed64,4,opt,name=client_mts,json=clientMts,proto3" json:"client_mts,omitempty"`
	RawResult  []byte  `protobuf:"bytes,5,opt,name=raw_result,json=rawResult,proto3,oneof" json:"raw_result,omitempty"`
}

func (x *SimulateRPCResponse) Reset() {
	*x = SimulateRPCResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRPCResponse) ProtoMessage() {}

func (x *SimulateRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRPCResponse.ProtoReflect.Descriptor instead.
func (*SimulateRPCResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{21}
}

func (x *SimulateRPCResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SimulateRPCResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SimulateRPCResponse) GetClientTick() uint64 {
	if x != nil {
		return x.ClientTick
	}
	return 0
}

func (x *SimulateRPCResponse) GetClientMts() float64 {
	if x != nil {
		return x.ClientMts
	}
	return 0
}

func (x *SimulateRPCResponse) GetRawResult() []byte {
	if x != nil {
		return x.RawResult
	}
	return nil
}

type SimulateForwardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*EntityStatus `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *SimulateForwardRequest) Reset() {
	*x = SimulateForwardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateForwardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateForwardRequest) ProtoMessage() {}

func (x *SimulateForwardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateForwardRequest.ProtoReflect.Descriptor instead.
func (*SimulateForwardRequest) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{22}
}

func (x *SimulateForwardRequest) GetEntities() []*EntityStatus {
	if x != nil {
		return x.Entities
	}
	return nil
}

type SimulateForwardResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*EntityStatus `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *SimulateForwardResponse) Reset() {
	*x = SimulateForwardResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateForwardResponse) ProtoMessage() {}

func (x *SimulateForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateForwardResponse.ProtoReflect.Descriptor instead.
func (*SimulateForwardResponse) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{23}
}

func (x *SimulateForwardResponse) GetEntities() []*EntityStatus {
	if x != nil {
		return x.Entities
	}
	return nil
}

type RTT struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartMts float64 `protobuf:"fixed64,1,opt,name=start_mts,json=startMts,proto3" json:"start_mts,omitempty"`
}

func (x *RTT) Reset() {
	*x = RTT{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTT) ProtoMessage() {}

func (x *RTT) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTT.ProtoReflect.Descriptor instead.
func (*RTT) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{24}
}

func (x *RTT) GetStartMts() float64 {
	if x != nil {
		return x.StartMts
	}
	return 0
}

type RTTACK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartMts    float64 `protobuf:"fixed64,1,opt,name=start_mts,json=startMts,proto3" json:"start_mts,omitempty"`
	ReceivedMts float64 `protobuf:"fixed64,2,opt,name=received_mts,json=receivedMts,proto3" json:"received_mts,omitempty"`
}

func (x *RTTACK) Reset() {
	*x = RTTACK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_world_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RTTACK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RTTACK) ProtoMessage() {}

func (x *RTTACK) ProtoReflect() protoreflect.Message {
	mi := &file_world_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RTTACK.ProtoReflect.Descriptor instead.
func (*RTTACK) Descriptor() ([]byte, []int) {
	return file_world_proto_rawDescGZIP(), []int{25}
}

func (x *RTTACK) GetStartMts() float64 {
	if x != nil {
		return x.StartMts
	}
	return 0
}

func (x *RTTACK) GetReceivedMts() float64 {
	if x != nil {
		return x.ReceivedMts
	}
	return 0
}

var File_world_proto protoreflect.FileDescriptor

var file_world_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x07,
	0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x12, 0x11, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x48, 0x00, 0x52, 0x01, 0x78, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a,
	0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x02, 0x52, 0x01, 0x7a, 0x88, 0x01, 0x01,
	0x42, 0x04, 0x0a, 0x02, 0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x79, 0x42, 0x04, 0x0a, 0x02,
	0x5f, 0x7a, 0x22, 0x70, 0x0a, 0x0a, 0x51, 0x75, 0x61, 0x74, 0x65, 0x72, 0x6e, 0x69, 0x6f, 0x6e,
	0x12, 0x11, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x01, 0x78,
	0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01,
	0x52, 0x01, 0x79, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x7a, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x48, 0x02, 0x52, 0x01, 0x7a, 0x88, 0x01, 0x01, 0x12, 0x11, 0x0a, 0x01, 0x77, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x48, 0x03, 0x52, 0x01, 0x77, 0x88, 0x01, 0x01, 0x42, 0x04, 0x0a, 0x02,
	0x5f, 0x78, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x79, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x7a, 0x42, 0x04,
	0x0a, 0x02, 0x5f, 0x77, 0x22, 0x20, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4a, 0x6f,
	0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x51, 0x75, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0xfb, 0x01, 0x0a, 0x0b, 0x53, 0x70, 0x77,
	0x61, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88, 0x01,
	0x01, 0x12, 0x37, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x01, 0x52, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x08, 0x72, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x61,
	0x74, 0x65, 0x72, 0x6e, 0x69, 0x6f, 0x6e, 0x48, 0x02, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x03, 0x52,
	0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06,
	0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0xfa, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x76, 0x65, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x37,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x01, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x3a, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x61, 0x74, 0x65, 0x72,
	0x6e, 0x69, 0x6f, 0x6e, 0x48, 0x02, 0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x88, 0x01, 0x01, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x03, 0x52, 0x05, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x42,
	0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09,
	0x5f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x63,
	0x61, 0x6c, 0x65, 0x22, 0x31, 0x0a, 0x0d, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x2e, 0x0a, 0x0a, 0x48, 0x69, 0x64, 0x65, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a,
	0x05, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x79, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01,
	0x12, 0x2a, 0x0a, 0x0e, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x61, 0x6e, 0x69, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x70, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x2a, 0x0a, 0x0e, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0d, 0x61, 0x6e,
	0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x88, 0x01, 0x01, 0x42, 0x07,
	0x0a, 0x05, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x61, 0x6e, 0x69, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x22, 0x8a, 0x04, 0x0a, 0x0a, 0x53,
	0x79, 0x6e, 0x63, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x2d, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0a,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x48, 0x01, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x88, 0x01, 0x01,
	0x12, 0x22, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x49,
	0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x05, 0x73, 0x70, 0x77, 0x61, 0x6e, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x77, 0x61, 0x6e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48,
	0x00, 0x52, 0x05, 0x73, 0x70, 0x77, 0x61, 0x6e, 0x12, 0x2f, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x48, 0x00, 0x52, 0x04, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x64, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x72,
	0x6f, 0x79, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x64, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x79, 0x12, 0x2f, 0x0a, 0x04, 0x68, 0x69, 0x64, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x48, 0x69, 0x64, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x04,
	0x68, 0x69, 0x64, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x61, 0x6e, 0x69,
	0x6d, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x41, 0x6e, 0x69,
	0x6d, 0x12, 0x3b, 0x0a, 0x09, 0x73, 0x74, 0x6f, 0x70, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74, 0x6f, 0x70, 0x41, 0x6e, 0x69, 0x6d, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x22, 0xc1, 0x01, 0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0c, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x10, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52,
	0x0e, 0x73, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x75, 0x69, 0x64, 0x88,
	0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f,
	0x72, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x42, 0x0d, 0x0a, 0x0b,
	0x5f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x0a, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x22, 0x66, 0x0a, 0x09, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x54, 0x69,
	0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x03, 0x6d, 0x74, 0x73, 0x12, 0x33, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xbc, 0x02,
	0x0a, 0x0c, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x04, 0x74, 0x69, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x48, 0x00, 0x52, 0x04,
	0x74, 0x69, 0x63, 0x6b, 0x88, 0x01, 0x01, 0x12, 0x22, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x6d, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x01, 0x52, 0x09, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x08, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x02, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x33, 0x48, 0x03,
	0x52, 0x08, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x31, 0x0a,
	0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63,
	0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x33, 0x48, 0x04, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x74, 0x73, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x72, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0xe1, 0x01, 0x0a,
	0x0b, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x31, 0x0a, 0x05,
	0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x12,
	0x40, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x48, 0x00, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x74, 0x73,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69, 0x63, 0x6b, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x63,
	0x6b, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x93, 0x01, 0x0a, 0x0c, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x74, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2c, 0x0a, 0x0f, 0x52, 0x61, 0x77, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77,
	0x44, 0x61, 0x74, 0x61, 0x22, 0x87, 0x01, 0x0a, 0x12, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x69,
	0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6d,
	0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x4d, 0x74, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x61, 0x72, 0x67, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61, 0x77, 0x41, 0x72, 0x67, 0x73, 0x22, 0x5a,
	0x0a, 0x11, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x50, 0x43, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x22, 0xbb, 0x01, 0x0a, 0x13, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x74, 0x69, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x6d, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4d, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0a, 0x72, 0x61, 0x77, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x72, 0x61, 0x77,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x72, 0x61,
	0x77, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x51, 0x0a, 0x16, 0x53, 0x69, 0x6d, 0x75,
	0x6c, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x52, 0x0a, 0x17, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22,
	0x22, 0x0a, 0x03, 0x52, 0x54, 0x54, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f,
	0x6d, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x4d, 0x74, 0x73, 0x22, 0x48, 0x0a, 0x06, 0x52, 0x54, 0x54, 0x41, 0x43, 0x4b, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x6d, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x6d, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x74, 0x73, 0x2a, 0x61, 0x0a,
	0x0a, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53,
	0x50, 0x57, 0x41, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x5f, 0x4d, 0x4f, 0x56, 0x45, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x10, 0x02, 0x12, 0x08,
	0x0a, 0x04, 0x48, 0x69, 0x64, 0x65, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x50, 0x4c, 0x41, 0x59,
	0x5f, 0x41, 0x4e, 0x49, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x12, 0x0a, 0x0e,
	0x53, 0x54, 0x4f, 0x50, 0x5f, 0x41, 0x4e, 0x49, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x05,
	0x2a, 0x1d, 0x0a, 0x11, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x50, 0x43, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x00, 0x2a,
	0x2b, 0x0a, 0x15, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x50, 0x43, 0x54, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x42, 0x0a, 0x5a, 0x08,
	0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_world_proto_rawDescOnce sync.Once
	file_world_proto_rawDescData = file_world_proto_rawDesc
)

func file_world_proto_rawDescGZIP() []byte {
	file_world_proto_rawDescOnce.Do(func() {
		file_world_proto_rawDescData = protoimpl.X.CompressGZIP(file_world_proto_rawDescData)
	})
	return file_world_proto_rawDescData
}

var file_world_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_world_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_world_proto_goTypes = []interface{}{
	(ActionType)(0),                 // 0: cluster_proto.ActionType
	(SimulateRPCMethod)(0),          // 1: cluster_proto.SimulateRPCMethod
	(SimulateRPCTicketCode)(0),      // 2: cluster_proto.SimulateRPCTicketCode
	(*Vector3)(nil),                 // 3: cluster_proto.Vector3
	(*Quaternion)(nil),              // 4: cluster_proto.Quaternion
	(*PlayerJoin)(nil),              // 5: cluster_proto.PlayerJoin
	(*PlayerQuit)(nil),              // 6: cluster_proto.PlayerQuit
	(*SpwanObject)(nil),             // 7: cluster_proto.SpwanObject
	(*MoveObject)(nil),              // 8: cluster_proto.MoveObject
	(*DestroyObject)(nil),           // 9: cluster_proto.DestroyObject
	(*HideObject)(nil),              // 10: cluster_proto.HideObject
	(*PlayAnimation)(nil),           // 11: cluster_proto.PlayAnimation
	(*StopAnimation)(nil),           // 12: cluster_proto.StopAnimation
	(*SyncAction)(nil),              // 13: cluster_proto.SyncAction
	(*ActionCommitted)(nil),         // 14: cluster_proto.ActionCommitted
	(*Response)(nil),                // 15: cluster_proto.Response
	(*RawMessage)(nil),              // 16: cluster_proto.RawMessage
	(*FrameTick)(nil),               // 17: cluster_proto.FrameTick
	(*EntityStatus)(nil),            // 18: cluster_proto.EntityStatus
	(*MoveRequest)(nil),             // 19: cluster_proto.MoveRequest
	(*MoveResponse)(nil),            // 20: cluster_proto.MoveResponse
	(*RawMessageGroup)(nil),         // 21: cluster_proto.RawMessageGroup
	(*SimulateRPCRequest)(nil),      // 22: cluster_proto.SimulateRPCRequest
	(*SimulateRPCTicket)(nil),       // 23: cluster_proto.SimulateRPCTicket
	(*SimulateRPCResponse)(nil),     // 24: cluster_proto.SimulateRPCResponse
	(*SimulateForwardRequest)(nil),  // 25: cluster_proto.SimulateForwardRequest
	(*SimulateForwardResponse)(nil), // 26: cluster_proto.SimulateForwardResponse
	(*RTT)(nil),                     // 27: cluster_proto.RTT
	(*RTTACK)(nil),                  // 28: cluster_proto.RTTACK
}
var file_world_proto_depIdxs = []int32{
	3,  // 0: cluster_proto.SpwanObject.position:type_name -> cluster_proto.Vector3
	4,  // 1: cluster_proto.SpwanObject.rotation:type_name -> cluster_proto.Quaternion
	3,  // 2: cluster_proto.SpwanObject.scale:type_name -> cluster_proto.Vector3
	3,  // 3: cluster_proto.MoveObject.position:type_name -> cluster_proto.Vector3
	4,  // 4: cluster_proto.MoveObject.rotation:type_name -> cluster_proto.Quaternion
	3,  // 5: cluster_proto.MoveObject.scale:type_name -> cluster_proto.Vector3
	0,  // 6: cluster_proto.SyncAction.type:type_name -> cluster_proto.ActionType
	7,  // 7: cluster_proto.SyncAction.spwan:type_name -> cluster_proto.SpwanObject
	8,  // 8: cluster_proto.SyncAction.move:type_name -> cluster_proto.MoveObject
	9,  // 9: cluster_proto.SyncAction.destory:type_name -> cluster_proto.DestroyObject
	10, // 10: cluster_proto.SyncAction.hide:type_name -> cluster_proto.HideObject
	11, // 11: cluster_proto.SyncAction.play_anim:type_name -> cluster_proto.PlayAnimation
	12, // 12: cluster_proto.SyncAction.stop_anim:type_name -> cluster_proto.StopAnimation
	18, // 13: cluster_proto.FrameTick.status:type_name -> cluster_proto.EntityStatus
	3,  // 14: cluster_proto.EntityStatus.position:type_name -> cluster_proto.Vector3
	3,  // 15: cluster_proto.EntityStatus.rotation:type_name -> cluster_proto.Vector3
	3,  // 16: cluster_proto.EntityStatus.scale:type_name -> cluster_proto.Vector3
	18, // 17: cluster_proto.MoveRequest.delta:type_name -> cluster_proto.EntityStatus
	18, // 18: cluster_proto.MoveRequest.prediction:type_name -> cluster_proto.EntityStatus
	18, // 19: cluster_proto.MoveResponse.result:type_name -> cluster_proto.EntityStatus
	18, // 20: cluster_proto.SimulateForwardRequest.entities:type_name -> cluster_proto.EntityStatus
	18, // 21: cluster_proto.SimulateForwardResponse.entities:type_name -> cluster_proto.EntityStatus
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_world_proto_init() }
func file_world_proto_init() {
	if File_world_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_world_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Vector3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quaternion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerJoin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerQuit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpwanObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DestroyObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HideObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayAnimation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAnimation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionCommitted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrameTick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RawMessageGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateRPCRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateRPCTicket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateRPCResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateForwardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateForwardResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTT); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_world_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RTTACK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_world_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*SyncAction_Spwan)(nil),
		(*SyncAction_Move)(nil),
		(*SyncAction_Destory)(nil),
		(*SyncAction_Hide)(nil),
		(*SyncAction_PlayAnim)(nil),
		(*SyncAction_StopAnim)(nil),
	}
	file_world_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[13].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[15].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[16].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[20].OneofWrappers = []interface{}{}
	file_world_proto_msgTypes[21].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_world_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_world_proto_goTypes,
		DependencyIndexes: file_world_proto_depIdxs,
		EnumInfos:         file_world_proto_enumTypes,
		MessageInfos:      file_world_proto_msgTypes,
	}.Build()
	File_world_proto = out.File
	file_world_proto_rawDesc = nil
	file_world_proto_goTypes = nil
	file_world_proto_depIdxs = nil
}
